### ISSUE TITLE
Stuck on Send to JabRef with MacOS

### ISSUE THREAD

**Issue by FilipeMaia** [JabRef/JabRef-Browser-Extension#177] opened 2020-06-04 14:47 UTC
I'm on MacOS 10.13.5 with JabRef 5.0 and Chrome 81.0.4044.138.
I've installed the extension from https://chrome.google.com/webstore/detail/jabref-browser-extension/bifehkofibaamoeaopjglfkddgkijdlh/
When using it, e.g. on https://www.nature.com/articles/s41598-020-65225-4 it gets stuck on `Send to JabRef...`
Looking into the developer console I see:
`TypeError: Cannot read property 'items' of null at chrome-extension://bifehkofibaamoeaopjglfkddgkijdlh/Zotero/translate_item.js:134`

**Comment by tobiasdiez** [comment] 2020-06-05 15:09
I think currently there is a problem with the setup on MacOS. 

As a workaround, you can follow the guidelines for the manual install: https://docs.jabref.org/collect/jabref-browser-extension#mac-os using this file:
https://github.com/JabRef/jabref/pull/6442/files#diff-d99aa77716bf8252215c6e3a02faf611
and replace the Firefox-specific parts by the paths outlined here: https://developer.chrome.com/apps/nativeMessaging

@LyzardKing is this fixed with https://github.com/JabRef/jabref/pull/6442 ?

**Comment by LyzardKing** [comment] 2020-06-05 21:37
Not having a mac to test this on does not simplify things...
@FilipeMaia Do you install from the .dmg or .pkg files?
There might be a difference in the way macos exposes the path variable.
https://github.com/JabRef/jabref/pull/6442 is a different issue, but this might help with that as well

**Comment by FilipeMaia** [comment] 2020-06-05 21:51
From .pkg.
Any more information I can give to help with debugging?

**Comment by LyzardKing** [comment] 2020-06-05 22:16
Is there any file in  /Library/Google/Chrome/NativeMessagingHosts?

**Comment by LyzardKing** [comment] 2020-06-05 22:17
specifically org.jabref.jabref.json

**Comment by FilipeMaia** [comment] 2020-06-06 08:03
No there isn't. Neither in `~/Library/Application Support/Google/Chrome/NativeMessagingHosts`

**Comment by FilipeMaia** [comment] 2020-06-06 08:06
The installation [instructions](https://docs.jabref.org/collect/jabref-browser-extension) mention `~/Library/Application Support/Mozilla/NativeMessagingHosts/`. Is that correct?

**Comment by FilipeMaia** [comment] 2020-06-06 08:09
I also noticed that [org.jabref.jabref.json](https://raw.githubusercontent.com/JabRef/jabref/master/buildres/linux/native-messaging-host/firefox/org.jabref.jabref.json) from the instructions page links to the Linux section of the tree and mentions a `/opt/jabref/lib/jabrefHost.py` which is not there nor could I find it anywhere.

**Comment by FilipeMaia** [comment] 2020-06-06 08:47
@tobiasdiez I tried to follow your suggestion but nothing really changed.

**Comment by tobiasdiez** [comment] 2020-06-06 11:20
Can you try to create the `/opt/jabref/lib/jabrefHost.py` file by downloading https://github.com/JabRef/jabref/blob/master/buildres/linux/jabrefHost.py.
Moreover, put https://github.com/JabRef/jabref/blob/1a546922787160ed447d3a6f63f068916e17e225/buildres/mac/native-messaging-host/chromium/org.jabref.jabref.json into `~/Library/Application Support/Google/Chrome/NativeMessagingHosts`.

This assumes that the JabRef executable is in `/opt/jabref/bin/JabRef`. If this is not the case, then every occurrence of `/opt/jabref/` (in the above instructions as well as in the json file) needs to be replaced by the right path.

I'm sorry for the inconvenience. Appearently you are the first mac user that tries the extension for Chrome ;-)

**Comment by FilipeMaia** [comment] 2020-06-06 12:22
No problem, thanks for the help :).
There is no `/opt/jabref`. JabRef is installed in `/Applications/JabRef.app/` as most MacOS apps.
I'll try to download the file as suggested an see what I can do with the paths.

**Comment by FilipeMaia** [comment] 2020-06-06 12:41
So I downloaded the `jabrefHost.py` into `/Applications/JabRef.app/Contents/runtime/Contents/Home/lib` and made it executable. I then edited to change the shebang to point to my python3 which is in `/usr/local/bin/python3`.
I finally edited `org.jabref.jabref.json` to point to the location in `/Applications`. And it now works! 
But clearly this should be improved...

**Comment by LyzardKing** [comment] 2020-06-06 14:34
... I'm looking at it in the previously mentioned PR, it wasn't it's main point, but it's probably a question of linking the correct files in the new buildres/mac folder

**Comment by LyzardKing** [comment] 2020-06-15 10:03
With the latest push on the PR (https://github.com/JabRef/jabref/pull/6442) the correct files should be included in the macos build.
The issue now is mostly with the install command, to copy the system files.. but it's a step in the right direction.
No more fiddling with the linux files in macos...hopefully we can keep the two separate (mostly)

**Comment by AriSchlesinger** [comment] 2020-09-02 20:26
Similar issue with Firefox on Mac
fixed locally following similar strategy to @FilipeMaia 

updated `jabrefHost.py`located at '/Applications/JabRef.app/Contents/Resources` to point hashbang to `/usr/local/bin/python3` (where python3 will be installed using Homebrew)
made `jabrefHost.py` executable. 

created new folder `NativeMessagingHosts` at path `/Users/ *yourUser* /Library/Application Support/Mozilla`
downloaded `org.jabref.jabref.json` into this folder
finally edited  `org.jabref.jabref.json` path to point to the executable located in `Applications/JabRef.app/Contents/Resources`

thx for the breadcrumbs :)

**Comment by MingLin-home** [comment] 2020-09-15 05:17
I have the same issue. JabRef 5.1, installed by DMG. Not lucky enough to make it work...

**Comment by LyzardKing** [comment] 2020-09-15 07:17
@AriSchlesinger @FilipeMaia 
Could you test something? Try replacing the hashbang with:
`#!/usr/bin/env python3`
This should fetch the correct python version without hardcoding it.
Thanks

**Comment by LyzardKing** [comment] 2020-09-15 07:21
@MingLin-home 
Can you verify that the file jabrefHost.py exists in `/Applications/JabRef.app/Contents/Resources`?
Also try changing the first line as described in the previous comment.

**Comment by clecap** [comment] 2020-09-20 18:35
Same problem here on MacOS 10.15.6

JabRef 5.1 installed via DMG.

jabrefHost.py confirmed in JabRef.app/Contents/Resources

shebang is /usr/bin/python3

/usr/bin/python3 is installed

org.jabref.jabref.json is in NativeMessagingHosts 

In Firefox: Extension does not show up
In Chrome: Extension throws ERR_FILE_NOT_FOUND

**Comment by coughingmouse** [comment] 2020-10-02 06:11
First time trying JabRef at all but No luck on Brave either.

1. Installed dmg,
1. placed the newer `~/Library/Application\ Support/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.jabref.jabref.json`,
1. changed jabrefHost.py shebang to `/usr/bin/env python3`
1. and copied it on `/Applications/JabRef.app/Contents/runtime/Contents/Home/lib` because I don't know what I'm doing.

But all I ever got was ERR_FILE_NOT_FOUND.

**Comment by LyzardKing** [comment] 2020-10-02 06:22
@clecap "org.jabref.jabref.json is in NativeMessagingHosts". In what folders?
It should be in:
`~/Library/Google/Chrome/NativeMessagingHosts` for chrome (and brave @coughingmouse )
`~/Library/Application Support/Mozilla/NativeMessagingHosts/<name>.json ` for firefox.

Let me know if those paths work.

**Comment by coughingmouse** [comment] 2020-10-02 07:55
@LyzardKing Why should it be placed in a Google folder for Brave? I don't even have Chrome installed. But if it were the case that there 're components that only work when the json file is in `.../Google/Chrome` directory, I'm guessing Brave or Ungoogled-chromium support needs to be added in the code as a feature.

I copied the json file onto the directory to see if it works, just to be clear, to no avail.

**Comment by LyzardKing** [comment] 2020-10-02 08:24
Brave (and many other browsers) are chrome-based, so they often use the same folder structure as chrome..
There are many issues (by looking at different support tickets on extensions) like the following:
https://github.com/browserpass/browserpass-native/issues/43#issuecomment-481794094
They seem to point to inconsistencies with the folder structure in brave.

Another path to try is: ~/Library/Application Support/Chromium/NativeMessagingHosts/

**Comment by clecap** [comment] 2020-10-02 10:32
Confirming that

* it is in the required folders.
* the JSON mentioned paths lead to a python file.
* the python interpreter mentioned in the shebang exists.

I still get the "ERR_FILE_NOT_FOUND" error. :-(

**Comment by AriSchlesinger** [comment] 2020-10-02 15:56
Heads up, in Firefox, it appears in the URL bar: 

<img width="516" alt="Screen Shot 2020-10-02 at 11 55 45" src="https://user-images.githubusercontent.com/52108669/94943824-4e51d480-04a6-11eb-82f9-40ed26327b95.png">

**Comment by AriSchlesinger** [comment] 2020-10-02 16:02
Have you all made the file `jabrefHost.py` executable?

(see links below on creating an executable if you are unsure)
https://superuser.com/questions/1164706/how-do-i-make-a-python-file-executable-on-macos-sierra
https://stackoverflow.com/questions/36564320/how-to-make-python-script-executable-on-osx

**Comment by AriSchlesinger** [comment] 2020-10-02 16:04
> @AriSchlesinger @FilipeMaia
> Could you test something? Try replacing the hashbang with:
> `#!/usr/bin/env python3`
> This should fetch the correct python version without hardcoding it.
> Thanks

I am fairly certain I tried this with no luck.

**Comment by LyzardKing** [comment] 2020-10-02 17:38
@AriSchlesinger 
Thanks for the testing...
Does it work with `#! /usr/bin/python3`?

**Comment by clecap** [comment] 2020-10-14 17:11
Yes, jabrefHost.py, which is in the JabRef.app Contents folder, is executable.

`/usr/bin/env python3` or `/usr/bin/python3` makes no difference in the reaction. ERR_FILE_NOT_FOUND error.

**Comment by tobiasdiez** [comment] 2021-01-19 22:02
Does this error still occurs? I don't have a mac, so I sadly cannot test this. @LyzardKing @Siedlerchr can you reproduce the ERR_FILE_NOT_FOUND  error?

**Comment by Siedlerchr** [comment] 2021-01-20 06:13
Firefox and jabref latest dev version on Mac I do not have any issues

**Comment by LyzardKing** [comment] 2021-01-20 07:40
@Siedlerchr does it work with the system version of python3? Without installing from other sources like brew?

**Comment by Siedlerchr** [comment] 2021-01-20 08:08
Good question, I  may have installed python3 form another source:
Python 3.9.0 (default, Nov 21 2020, 14:55:42)

**Comment by LyzardKing** [comment] 2021-01-20 09:24
what do you get if you run `which python3` in the terminal?

**Comment by Siedlerchr** [comment] 2021-01-20 09:26
`/usr/local/bin/python3`

**Comment by LyzardKing** [comment] 2021-01-20 09:38
As far as I can tell that should be the version pulled from the python website... 
brew should install in a /cellar/... dir, and the system version should be in /ust/bin/python3...
The strange thing is that the env shebang doesn't work...

**Comment by Siedlerchr** [comment] 2021-01-20 09:46
hm, I only found this thread here https://stackoverflow.com/questions/52969383/shebang-line-for-python-does-not-work-at-all 
maybe something with permissions?

**Comment by tobiasdiez** [comment] 2021-01-30 10:57
So it seems this is fixed now, right?

**Closed by tobiasdiez** 2021-01-30 10:57 UTC
Labels: status:jabref, status:waiting-for-feedback, type:bug

**Comment by clecap** [comment] 2021-01-31 22:16
@tobiasdiez thank you for coming back on this.

I installed JabRef and the extension from a completely new download to test it.

Result: I cannot test this error as now there is a new error which does not let me test this effect any longer. I get stuck at "searching bibliographic data" and get a "cannot read property of configOptions of undefined" error in the browser console. See my new issue. 

Sorry for that
