### ISSUE TITLE
Crash right after a successful import on Chrome and Edge on Windows 10

### ISSUE THREAD

**Issue by SlaggyWolfie** [JabRef/JabRef-Browser-Extension#364] opened 2021-10-12 07:12 UTC
Whenever I (successfully) import an entry in JabRef via the browser extension it immediately crashes on Chrome and Edge on Windows 10. Chrome is my main browser so it has a boat-load of other extensions including an AdBlocker. However, I tested with Edge and it still crashed. I am a bit aware that Edge is just Chromium under the hood, but I genuinely have no idea why. I white-listed Zotero via the AdBlock as well via the Troubleshooting section for this in the wiki and I am NOT using a portable version of JabRef. The console as far as I am aware did not produce any kind of errors, the extension just crashes out of nowhere. Thankfully, I can reload it as a push-up prompt but I am of the habit that I don't often close my PC or browser so I might fail to reload the plugin forcing me to restart my 70 tab session.

I tested the extension with Firefox and it appears to work fine with no (visible) crashes.

Any help would be appreciated, though I apologize if this issue is not very helpful (not following any templates) or it has already been posted about.

**Comment by SlaggyWolfie** [comment] 2021-10-20 10:46
Any updates?

**Comment by ohusiev** [comment] 2021-10-20 22:41
Recently tried to use JabRef and also got the same issue with the browser extension for Chrome (on Windows 10).  It's crushing after each click to add a source via an extension (to already manually opened JabRef Desktop).

**Comment by SlaggyWolfie** [comment] 2021-11-02 11:32
@tobiasdiez

**Comment by tobiasdiez** [comment] 2021-11-26 14:44
Sorry for the late response.

I sadly cannot reproduce this on Win 11 + Chrome  96.0.4664.45 (Official Build) (64-bit). Maybe the recent update fixed it?

If you still experience this, can you please open the "Developer tools" (Ctrl + Shift + I) and go to console. Then try to import into Jabref and copy everything that is displayed in the console.

**Comment by janikmu** [comment] 2021-12-28 14:55
I don't know if this is the same/a similar issue, or unrelated, but I observe the following behavior:

I have Jabref opened and I import something from the browser extensions (2.4 on Edge 96.0.1054.62 (Official Build) (64-bit)). This successfully opens the import dialog in the existing Jabref application window but also opens another Jabref instance with the same import dialog. I can successfully complete the import in the already opened Jabref instance or the newly opened one but when I close any of the two Jabref instances, the browser extension crashes.
No browser log in the console. I also can't enable Chromium logging, work machine.

```
JabRef 5.4--2021-12-20--ab44182
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1
```

**Comment by tobiasdiez** [comment] 2022-01-07 20:16
Strange. Can you make sure you have "Remove operation" enabled in JabRef under Options > Preferences > Network. Then you should only get once JabRef instance, regardless of how you open/import something.

**Comment by tobiasdiez** [comment] 2022-01-23 15:44
Closing this as it seems to be resolved. If the error still persist, just let me know and I'll reopen it.

**Closed by tobiasdiez** 2022-01-23 15:44 UTC
Labels: type:bug, status:waiting-for-feedback
