### ISSUE TITLE
Common websites dont work

### ISSUE THREAD

**Issue by diabl0w** [JabRef/JabRef-Browser-Extension#90] opened 2019-11-13 14:43 UTC
Common websites like NCBI's pubmed (example: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3762248/) and ScienceDirect (https://www.sciencedirect.com/science/article/abs/pii/S1040842803002750?via%3Dihub) are not detected by jabfox and the option to import is grayed out. 

These are very fundamental websites... zotero detects them fine

**Comment by diabl0w** [comment] 2019-11-13 18:01
also pdf's opened in browser do not have an import option either... example: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3123451/pdf/nihms288491.pdf

**Comment by diabl0w** [comment] 2019-11-13 19:58
Site: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3123451/

Log:

JabFox: Searching for translators for  
Object { id: 1, index: 0, windowId: 1, highlighted: true, active: true, attention: false, pinned: false, status: "loading", hidden: false, discarded: false, … }
background.js:68:10
ReferenceError: TLDS is not defined proxy.js:626:11
Messaging: Received message: Prefs.getAll,
Messaging: Received message: Translators.getWebTranslatorsForLocation, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3123451/,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3123451/ messaging.js:53:11

ReferenceError: TLDS is not defined at moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging_inject.js:76 zotero.js:284:12
Messaging: Received message: Errors.log, TLDS is not defined
Zotero.Proxies</this.getPotentialProxies@moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/proxy.js:626:11
Zotero.Translators</this.getWebTranslatorsForLocation<@moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/translators.js:188:39
Zotero.Promise.method/<@moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/promise.js:34:17
Zotero.Messaging</this.receiveMessage<@moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:85:20
Zotero.Promise.method/<@moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/promise.js:34:17
Zotero.Messaging</this.init/<@moz-extension://e64d880e-e9a8-4941-8c3a-98a3a3e46fa6/Zotero/messaging.js:214:29
messaging.js:53:11
Messaging: Received message: Debug.log, Translate: All translator detect calls and RPC calls complete:, messaging.js:53:11
(3)(+0032258): Translate: All translator detect calls and RPC calls complete: debug.js:171:20
JQMIGRATE: jQuery.fn.live() is deprecated jig.min.js:5:26203
console.trace() jig.min.js:5:26271
    migrateWarn https://www.ncbi.nlm.nih.gov/core/jig/1.14.8/js/jig.min.js:5
    live https://www.ncbi.nlm.nih.gov/core/jig/1.14.8/js/jig.min.js:6
    <anonymous> https://static.pubmed.gov/portal/portal3rc.fcgi/4160049/js/3879255/4121861/3818874/4168176/3821238/4117325/4087685/4072593/4076480/3921943/4105668/4065628.js:895
    each https://www.ncbi.nlm.nih.gov/core/jig/1.14.8/js/jig.min.js:2
    each https://www.ncbi.nlm.nih.gov/core/jig/1.14.8/js/jig.min.js:2
    interval https://static.pubmed.gov/portal/portal3rc.fcgi/4160049/js/3879255/4121861/3818874/4168176/3821238/4117325/4087685/4072593/4076480/3921943/4105668/4065628.js:880
Messaging: Received message: Debug.log, 	No suitable translators found, messaging.js:53:11
(3)(+0000001): 	No suitable translators found debug.js:171:20
Messaging: Received message: Prefs.getAsync, reportTranslationFailure messaging.js:53:11
TypeError: translators is undefined

**Comment by LyzardKing** [comment] 2019-11-13 23:38
The SienceDirect link works on my end with the latest jabref and the firefox extension..
What error do you see if you load that page?

**Comment by diabl0w** [comment] 2019-11-13 23:48
> The SienceDirect link works on my end with the latest jabref and the firefox extension..
> What error do you see if you load that page?

you are correct, it does work... I am not sure why I got that one confused

**Comment by tobiasdiez** [comment] 2019-12-15 22:51
A few more examples:
https://aip.scitation.org/doi/10.1063/1.4896698
https://link.springer.com/book/10.1007/978-3-642-31558-9
https://link.springer.com/article/10.1007%2Fs11005-017-1018-z#Bib1
https://www.worldscientific.com/doi/abs/10.1142/S0129055X19500168

**Comment by tobiasdiez** [comment] 2019-12-17 12:20
Google Scholar and Google books also does not work...

**Comment by LyzardKing** [comment] 2019-12-17 17:08
@tobiasdiez I just tested now and both google scholar and google books work for me
with the latest jabref beta and jabfox installed in firefox
The other links don't work, and the error they report is:
`ReferenceError: require is not defined at moz-extension://9227f5a0-a84d-4c86-a6e5-67c027d8b8fa/Zotero/http.js:233`
It's strange, because from the zotero import jabfox should have inherited their require shim...

**Comment by LyzardKing** [comment] 2019-12-17 17:14
granted..in scholar it imports from the search method, not exactly a useful feature..

**Comment by PorcelainMouse** [comment] 2020-01-02 18:18
Hmm, now this *was* working for me before I checked the box in JabRef to communicate over port 6050; I think just about any web-page would allow me to click the JabFox icon.  Now, many journal article web-pages don't allow import.  Confusing.  Here are some more examples.

 https://doi.org/10.1063/PT.3.4389 (and all other Physics Today articles)
 https://doi-org/10.1088/0143-0807/28/3/E01 (and all Eur. J. Physics articles)
 https://doi-org/10.1119/10.0000145 (all Am. J. Physics articles, all AAPT published articles?)
 https://doi-org/10.3847/1538-4357/ab5956 (hmm, all IOP publish articles?)
 
FWIW, also I cannot import things from my library web-site, either.  Hmm, this is pretty unusable.

Now, I can import NYtimes.com articles and some random web-pages that are not articles.  So, I see that it works sometimes, just not on articles I'm trying to import.

**Comment by bernhard-kleine** [comment] 2020-03-02 16:40
I had an issue with this site: 10.1210/endocr/bqaa002. While other papers from the same issue could be imported via Jabfox directly, I had to use zotero for this one. Upon reloading the page, I got the Jabfox symbol. Maybe you understand this?

**Comment by systemoperator** [comment] 2020-03-02 18:09
Could be related to #124.

**Comment by tobiasdiez** [comment] 2020-03-14 15:50
This should be fixed in the next release.

**Comment by bernhard-kleine** [comment] 2020-03-14 15:52
the lastest master is from 12.03.2020. Do we have to wait?

**Comment by tobiasdiez** [comment] 2020-03-14 17:11
The releases of the browser extension are independent of the JabRef releases. I'll push a new update to the firefox/chrome store this evening. Should then be automatically installed in a few days.

**Comment by diabl0w** [comment] 2020-03-14 17:40
thanks for your continued support on this project!

**Comment by bernhard-kleine** [comment] 2020-03-14 18:58
I appreciate the JabFox-Add-on very much. I actually like it. It smoothens the process of citation collection quite well. My working with literature citations started with "Lochkarten" and via biblio by Verlag Chemie, Endnote, Pybliographer I arrived at Jabref which is now most comfortable. JabFox is the crown to it.

**Comment by tobiasdiez** [comment] 2020-03-14 19:27
Thanks for the kind words! I'm happy to help you guys having fun with your literature ;-).

The new version (2.2) is uploaded and already accepted. Thus the installed extension should automatically update.

**Comment by eugenio** [comment] 2020-11-12 14:49
I believe I have a similar issue with Google-Chrome.
In the console I see  some errors whose trace i attached in [log](https://github.com/JabRef/JabRef-Browser-Extension/files/5531299/sfamjournals.onlinelibrary.wiley.com-1605192221589.log)
the page is : [https://sfamjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1462-2920.14842](https://sfamjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1462-2920.14842) .
Should this issue be reopened?

**Comment by tobiasdiez** [comment] 2020-11-12 21:42
> zotero.js:309 ReferenceError: TLDS is not defined at chrome-extension://bifehkofibaamoeaopjglfkddgkijdlh/Zotero/proxy.js:626

That points to a problem because I guess you have a proxy enabled (tracked in #153).

**Comment by eugenio** [comment] 2020-11-13 08:52
@tobiasdiez I tried both with connection behind proxy (my  dorm connection) and a cell connection (my own cellular connection); it always gives the same error...
I tried with my university manual proxy, with the same result. I think we can conclude that it is not a proxy issue.

**Comment by LyzardKing** [comment] 2020-11-13 09:04
@tobiasdiez I can confirm this issue.
I tested it and the jabref icon in chrome doesn't activate (it opens the contextual menu, as if it wasn't on a parsable page)

**Comment by tobiasdiez** [comment] 2020-11-13 09:34
Ok, my bad! Thanks for testing. @eugenio could you please open a new issue, as the problem seems to be specific to chrome.

**Comment by eugenio** [comment] 2020-11-13 09:39
@tobiasdiez, yes no problem! Shall I copy the message content of my two posts? or just reference this issue?

**Comment by LyzardKing** [comment] 2020-11-13 09:59
It works if I run from master.
There might be some change that is not yet available in the released version

**Comment by eugenio** [comment] 2020-11-13 10:22
@LyzardKing i cannot seem to be able to install it from git's master.... I give sudo ./install_linux.sh in a terminal and the menu appears but after the process ends the extension isn't in chrome even after restarting chrome... what am I missing?

**Comment by LyzardKing** [comment] 2020-11-13 10:34
The install script only adds a file needed to communicate with the extension and the program (jabref).
To test from master you would need to install npm and web-ext..
and it would only be temporary... so it's not really the best way to install.
@tobiasdiez Could you test that master works? There might have been something we imported from zotero that is not in the released version yet.. What do you think?

**Comment by tobiasdiez** [comment] 2020-11-13 11:14
You are right, the published Chrome extension is still on 2.1.2 while the master (and firefox) is 2.2. 

I hope I find the time this weekend and invest time into the extension again, fixing some of the remaining issues and publishing a new version to all browser stores.
@eugenio if you want to try out the master, follow https://github.com/JabRef/JabRef-Browser-Extension#contributing-to-the-development and use `npm run dev:chrome`.

**Comment by LyzardKing** [comment] 2020-11-13 11:20
@tobiasdiez Could the upload process be automated?
With something like https://github.com/LinusU/wext-shipit

**Comment by eugenio** [comment] 2020-11-13 11:22
@tobiasdiez thanks for the tip and for the great work!

**Comment by stiftle** [comment] 2021-01-09 18:25
> You are right, the published Chrome extension is still on 2.1.2 while the master (and firefox) is 2.2.
> 
> I hope I find the time this weekend and invest time into the extension again, fixing some of the remaining issues and publishing a new version to all browser stores.

Hello,
could someone push the current version to Chrome (as far as I understand, the code for Firefox, where it works and Chrome is equal and therefore no changes would be necessary) since Chrome is by far the most common browser?

However, this extension is absolutely awesome if it works!

Thanks a lot for your work!

**Comment by tobiasdiez** [comment] 2021-01-20 19:25
As said above, the issue is fixed in the most recent version. I'll push an update to the store in the next few days! Sorry for the inconvenience caused.

**Closed by tobiasdiez** 2021-01-20 19:25 UTC
Labels: status:accepted, type:bug
