### ISSUE TITLE
Error message in browser console

### ISSUE THREAD

**Issue by clecap** [JabRef/JabRef-Browser-Extension#271] opened 2021-01-31 22:06 UTC
This is about extension version 2.4 installed on Chrome 88.0.4324.96 (Official Build) (x86_64) on MacOs 10.15.6 on a google scholar page with Jabref 5.2.

The extension is freshly installed and reports an error in the browser console as follows:
![Screenshot 2021-01-31 at 23 06 12](https://user-images.githubusercontent.com/7084049/106399453-f5288c00-6418-11eb-853f-d205a2a52c33.png)

**Comment by tobiasdiez** [comment] 2021-02-12 22:35
Thanks for your report. I cannot reproduce this. Could you please provide the url where the error occurs.

**Comment by clecap** [comment] 2021-03-02 13:07
I still can reproduce this. A url is an arbitrary google scholar page. For example

https://scholar.google.de/scholar?hl=en&as_sdt=0%2C5&q=Bohr&btnG=

**Comment by tobiasdiez** [comment] 2021-03-02 15:36
Does it also happen on other websites? Google scholar is a bit tricky, since google is very aggressively blocking access.

**Comment by clecap** [comment] 2021-03-02 23:22
I experimented a bit with it on Google and I see what you mean. It seems not to be connected to the Zotero / Ad Block Plus problem. I have not seen that problem on different sites (but the reason may be that, due to another issue, which I also reported but which was closed prematurely) the extension is not working on any site for me (just the reasons vary).

That said...it would be great if the extension would deliver a bit more meaningful error messages as it does currently ;-) or be refactored in a way that it depended less on other parts and reported more clearly when which part failed. I am not trying to be super smart here it is just...I NEVER got the extension running and recognize quite a bit of the issues reported here in other instances. If the extension reported more clearly where (in which dependency) it was failing, the overall issue search would be much easier.

**Comment by tobiasdiez** [comment] 2022-01-23 16:00
This particular error is a duplicate of https://github.com/JabRef/JabRef-Browser-Extension/issues/280.

The error handling has been improved in the new version (to be released in a few days) so hopefully it is working now for you on other pages, or at least you should get a more meaningful error.

**Closed by tobiasdiez** 2022-01-23 16:00 UTC
Labels: type:bug, status:waiting-for-feedback
