### ISSUE TITLE
Jabfox not always importing.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/JabRef-Browser-Extension#133] opened 2020-02-11 10:41 UTC
JabRef 5.0-beta.409--2020-02-09--6a9c915
Windows 10 10.0 amd64 
Java 13.0.2 
- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I have found at least two entries which can not be imported into Jabref by Jabfox:
 https://doi.org/10.1038/s41586-019-1168-5 and https://journals.physiology.org/doi/abs/10.1152/ajpendo.00121.2019
1. Open Jabref(5)
2. go to one of the above mentioned websites and try to import them via the Jabfox button.
3. You are stuck with "searching for bibliographical data".

Other entries could be at the same time be successfully imported.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment] 2020-02-13 14:58
Moved the issue to the Browser Extension repo.

**Comment by tobiasdiez** [comment] 2020-03-09 20:20
This should be fixed now and the fix will be included in the next release.

**Comment by bernhard-kleine** [comment] 2020-03-09 22:28
Thanks a lot: DOI 10.1126/science.aap8328  which has not been imported via Jabfox this afternoon, now imports properly. Good work!

**Comment by bernhard-kleine** [comment] 2020-03-16 17:16
With the new version (2.2), DOI: 10.1126/science.aav8573 is not imported.

**Comment by bernhard-kleine** [comment] 2020-03-16 17:52
DOI: 10.1126/science.aav2501 was also not imported.

**Comment by tobiasdiez** [comment] 2020-03-16 17:52
Can reproduce this problem. Error:
> TypeError: data is undefined at moz-extension://0e2ffb6f-f4e6-4cba-8631-9f4c7eb772fe/Zotero/translate_item.js:134

**Comment by bernhard-kleine** [comment] 2020-03-16 18:10
I could, however, import all the citations with Zotero.

**Comment by LyzardKing** [comment] 2020-03-16 18:18
I just tried https://doi.org/10.1126/science.aav2501 and it works on my system.
I'm using the latest snap on ubuntu and the latest extension

**Comment by bernhard-kleine** [comment] 2020-03-16 19:02
I updated to the last master and still no import: JabRef 5.1--2020-03-12--23034ce.

**Comment by bernhard-kleine** [comment] 2020-03-21 17:17
I just found anotherone not importing: 10.1016/j.neuron.2019.10.006

**Comment by funnym0nk3y** [comment] 2020-03-28 23:13
For me this issue is not consistent with time. Usually I have issues with articles from [](https://aip.scitation.org), but a fresh start usually solves it.

**Comment by koppor** [comment] 2020-09-04 12:55
Refs https://github.com/JabRef/jabref/issues/6832#issuecomment-686505405

**Comment by tobiasdiez** [comment] 2021-01-20 19:19
I've tried all links in this issue with the new version of the extension (to be released soon) and everything worked.

The only exception was https://science.sciencemag.org/content/364/6438/eaav2501, which failed because "The command line is too long". This is tracked at https://github.com/JabRef/JabRef-Browser-Extension/issues/49.

**Closed by tobiasdiez** 2021-01-20 19:19 UTC
Labels: status:accepted, type:bug
