### ISSUE TITLE
Error connecting to jabref - powershell issue

### ISSUE THREAD

**Issue by funnym0nk3y** [JabRef/JabRef-Browser-Extension#449] opened 2022-04-27 10:12 UTC
With the installation of Jabref 5.6 the browser extension seems broken. 
![grafik](https://user-images.githubusercontent.com/41870754/165495158-5c643c5c-1004-499a-b838-821e668be83b.png)
![grafik](https://user-images.githubusercontent.com/41870754/165495236-e05a7715-66ab-48e3-8a37-0b5ad6db5ad1.png)
As the messages indicate, there is an issue with powershell. But contrary to that powershell is installed and working fine: 
![grafik](https://user-images.githubusercontent.com/41870754/165495740-53065c78-a448-47ed-97b9-d1d05c4a77a0.png)

**Comment by lmsteffan** [comment] 2022-04-28 08:54
I have the same problem since I updated to 5.6.

(hope this message is not a breach of etiquette, I simply want to confirm that the problem is not unique to the OP).

**Comment by marinovaiva** [comment] 2022-04-28 12:09
+1
JabRef browser extension cannot seem to find powershell.exe
![image](https://user-images.githubusercontent.com/73995347/165748829-b0295ef8-dc8a-4ac4-9bed-3d282be34b9e.png)
I do have the lastest PowerShell installed

**Comment by tobiasdiez** [comment] 2022-04-28 12:19
Strange. Could you please run the following commands in a command line and report their output. Thanks!
```cmd
where pwsh.exe
pwsh.exe -version

where powershell.exe
$PSVersionTable.PSVersion
```

**Comment by funnym0nk3y** [comment] 2022-04-28 12:59
This is the result for me: 
![grafik](https://user-images.githubusercontent.com/41870754/165757548-6cd68cb1-9f69-4507-ba51-999a9bb66f31.png)

It seems that `where` does not work from within powershell. So from cmd:
![grafik](https://user-images.githubusercontent.com/41870754/165757424-ea576775-e557-4a3f-a756-7420c65909b9.png)

**Comment by dirkziegenbalg** [comment] 2022-05-08 12:11
> I had the same problem; updating/reinstalling PowerShell 7 (https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2), then reinstalling the JabRef browser extension and restarting the browser helped.

I can confirm that installing PowerShell solves the issue somehow and sends the citation to JabRef but simultaneously the browser extension also crashes in Vivaldi. I only had the PowerShell which ships with Windows 10 before hand and the extension worked quite some time, finally ending in the issue described above.

**Comment by cryptonoel** [comment] 2022-06-02 12:33
What solved the issue for me was to update the `JabRefHost.bat` file located in the same directory as the `JabRef.exe` to

```bat
@echo off
pushd %~dp0

where /q powershell.exe
if %errorlevel%==0 (
    @powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -WindowStyle Hidden -File ".\JabRefHost.ps1"
) else (
    echo "Could not find pwsh.exe or powershell.exe" 1>&2
    echo "Please install PowerShell and try again." 1>&2
    exit /b 1
)
```

**Comment by funnym0nk3y** [comment] 2022-06-02 12:47
@cryptonoel I don't get it. My file looks like this, and I think that should work too: 

```powershell
@echo off
pushd %~dp0

:: Test if pwsh exists
where /q pwsh.exe
if %errorlevel%==0 (
    @pwsh.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -WindowStyle Hidden -File ".\JabRefHost.ps1"
) else (
    :: If not, test if powershell exists
    where /q powershell.exe
    if %errorlevel%==0 (
        @powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -WindowStyle Hidden -File ".\JabRefHost.ps1"
    ) else (
        echo "Could not find pwsh.exe or powershell.exe" 1>&2
        echo "Please install PowerShell and try again." 1>&2
        exit /b 1
    )
)
```

**Comment by cryptonoel** [comment] 2022-06-02 13:09
@funnym0nk3y I agree with you that logically they are the same. However, when I removed the `pwsh` branch it worked. I didn't have time to look into why. With regards to your new error it seems that `powershell` is now being called correctly because that error message seems to be coming from the JSON parser launched via `powershell`.

**Comment by Leative** [comment] 2022-07-12 16:12
While I am not a big windows command line user I realized that the batch script has a flaw.
The environment variable `%errorlevel%` is not always updated when the error level changes. Therefore, if the invocation of `where /q pwsh.exe` returns 1 the check in the second if-condition may still read this value regardless of whether or not the invocation to `where /q powershell.exe` was successful.
The correct implementation of the conditionals would be `if not errorlevel 1`. Cheers.

**Comment by Leative** [comment] 2022-07-12 16:38
Trying to submit a fix I realize a fix has been applied just 20 hours ago: https://github.com/JabRef/jabref/commit/2a82b9aa4c996283a346d5d7fda3f6100c883fc4
Works for me. I guess this issue can be closed.

**Comment by tobiasdiez** [comment] 2022-07-12 21:02
@Leative Indeed, @Tobi0 was a bit quicker. Thanks for your investigation and for confirming that the fix works as expected.

Closing as this will be fixed with the next JabRef release.

**Closed by tobiasdiez** 2022-07-12 21:02 UTC
Labels: type:bug, status:waiting-for-feedback, env:win
