### ISSUE TITLE
Error connecting to JabRef

### ISSUE THREAD

**Issue by ghost** [JabRef/JabRef-Browser-Extension#448] opened 2022-04-26 14:50 UTC
I get an error message when trying to import a reference from Google Scholar using the JabRef Browser extension. I tried both Firefox and Chrome, but with the same results. 

The error message states "Error connecting to JabRef" with the subheading "Specified native messaging host not found."

OS: MacOs 12.3.1

Hope you can help. Please write if you need more information on the issue.

**Comment by AriSchlesinger** [comment] 2022-04-28 23:26
Hi! Try to make the .py file executable: https://superuser.com/questions/1164706/how-do-i-make-a-python-file-executable-on-macos-sierra

**Comment by tobiasdiez** [comment] 2022-09-07 13:00
Duplicate of #461

**Closed by tobiasdiez** 2022-09-07 13:00 UTC
