### ISSUE TITLE
Mac OS 12.6: Chrome/Firefox: Error message should contain Mac OS X hints

### ISSUE THREAD

**Issue by koppor** [JabRef/JabRef-Browser-Extension#494] opened 2022-09-28 15:08 UTC
As of today on Mac OS 12.6:

![image](https://user-images.githubusercontent.com/1366654/192815722-f5824e7b-09ea-46da-843a-27b8f8ca28ea.png)

Same for Firefox:

![image](https://user-images.githubusercontent.com/1366654/192815814-2f39e4e5-2352-4488-b14d-d1a12d6c6dbd.png)

---

![image](https://user-images.githubusercontent.com/1366654/192816563-0ade3ba6-3e8c-4817-804d-a1fca79560df.png)

**Comment by tobiasdiez** [comment] 2022-09-28 16:15
Duplicate of #405

**Closed by tobiasdiez** 2022-09-28 16:15 UTC
