### ISSUE TITLE
"Error Connecting to JabRef" in Chrome on Win10

### ISSUE THREAD

**Issue by orionpilot** [JabRef/JabRef-Browser-Extension#566] opened 2023-04-24 20:58 UTC
Quickly looking at the open issues, #493 seems to be the closest to what I am experiencing. Since I have been using JabRef + Extension for a while and only recently have had this issue, I think a recent update is the cause.

JabRef version: 

- JabRef 5.9--2023-01-08--76253f1a7
- Windows 10 10.0 amd64 
- Java 19.0.1 
- JavaFX 19+11

I have tried uninstalling and removing the extension from Chrome, issue persists. I have tried following the manual instructions, but since I am not familiar in powershell, I can't tell that step 4 is correct. This is the relevant line from the `.ps1` file:

<img width="464" alt="jabref_ps1_powershell" src="https://user-images.githubusercontent.com/32915653/234114097-00a3d90b-641e-4475-9116-7613c37c4be5.png">

The Chrome console message is: 
![image](https://user-images.githubusercontent.com/32915653/234113801-bff8d011-0d36-4b98-8603-b7d88e462288.png)

The error code from the error page is: 
![image](https://user-images.githubusercontent.com/32915653/234114226-e8fd1205-b3e4-4723-80af-d629b4872da2.png)

From #493, uncommenting the debugging lines in `JabRefHost.ps1` and importing a reference does produce a pop up: 

![image](https://user-images.githubusercontent.com/32915653/234113274-5bae9f52-b78b-4c7a-ad1f-d578823f653e.png)

Again, the reference is properly added, I just also get the browser error message. Hopefully there's been some progress!

**Comment by tobiasdiez** [comment] 2023-05-01 08:41
Thanks for reporting this, but it is indeed a duplicate of #493. I was able to reproduce the issue, but haven't yet found the time to fix it. Sorry...

**Closed by tobiasdiez** 2023-05-01 08:41 UTC
