### ISSUE TITLE
Error connecting to JabRef - sends the reference fine

### ISSUE THREAD

**Issue by tbritesribeiro** [JabRef/JabRef-Browser-Extension#608] opened 2024-03-19 19:57 UTC
When I use the chrome extension it sends the reference to JabRef, without anyother problem but for every single reference I send a new tab opens with this.

![image](https://github.com/JabRef/JabRef-Browser-Extension/assets/162701629/c43a7e0d-8472-46ce-ab84-5eb1a52a108a)

In the console of that tab, this appears: 

(index):62 cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation

**Comment by ror3d** [comment] 2024-03-20 15:37
Seems duplicate of #493, which should have been fixed in the latest build of JabRef, could you check if downloading/installing JabRef from https://builds.jabref.org/main/ you still see this issue?

**Closed** 2024-03-26 14:29 UTC
